
default: &default
  adapter: mysql2
  database: yoitsu
  encoding: utf8
  port: 3306

development:
  <<: *default
  host: localhost
  username: tim
  password: admin

production:
  <<: *default
  host: localhost
  username: <%= ENV["SQL_NAME"] %>
  password: <%= ENV["SQL_PASSWORD"] %>